server:
  port: 8123
spring:
  datasource:
    #    测试
    pg:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://10.0.97.249:5432/java_frame
      username: postgres
      password: 1qaz@WSX
      type: com.alibaba.druid.pool.DruidDataSource
    hive:
      driver-class-name: org.apache.hive.jdbc.HiveDriver
      jdbc-url: jdbc:hive2://10.1.1.104:10000/test
      username: hadoop
      password: hadoop
      type: com.alibaba.druid.pool.DruidDataSource
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.0.97.31:3306/soul?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
    #      正式
#    pg:
#      driver-class-name: org.postgresql.Driver
#      jdbc-url: jdbc:postgresql://10.1.1.120:5432/etl
#      username: postgres
#      password: 123456
#      type: com.alibaba.druid.pool.DruidDataSource
#    hive:
#      driver-class-name: org.apache.hive.jdbc.HiveDriver
#      jdbc-url: jdbc:hive2://10.1.1.104:10000/test
#      username: hadoop
#      password: hadoop
#      type: com.alibaba.druid.pool.DruidDataSource
#    mysql:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://10.1.1.103:3306/metastore?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#      username: root
#      password: Bigdata@123
#      type: com.alibaba.druid.pool.DruidDataSource

  common-config:
      initialSize: 1
      minIdle: 1
      maxIdle: 5
      maxActive: 50
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 10000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      filters: sta
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true


logging:
  pattern:
    console: "%d -%msg%n"
  level:
    root: info
#测试标记
custom:
  yml_sign: "0"
#正式标记
#custom:
#  yml_sign: "1"







